name: compile

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://stackoverflow.com/a/77140873
      - name: Set up C/C++ and compile code
        shell: cmd
        run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && cl /Zi /D _UNICODE /D UNICODE main.c User32.lib Gdi32.lib Shlwapi.lib Shell32.lib Pathcch.lib /Fe:screenshot-debug.exe' }} 

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: screenshot-debug.exe
